### PR TITLE
Fix error in console

### LINKED ISSUE #81: JavaScript error in editor
- Add a new page or post.
- Open the DevTools Console.
- See the following error:

Screenshot 2022-11-10 at 8 38 33 AM

### PR DESCRIPTION
**Pull request by Imran92**
Fixes https://github.com/Automattic/course/issues/81

## Changes proposed

Fixed the error that was shown in the console on the editor page

## Testing instructions

- Create a new post or page with the console open
- Make sure there is no error in the console

### CODE REVIEW

**Review by LavaGolem — APPROVED** [review]

File: functions.php [hunk 1]
```diff
@@ -54,31 +54,13 @@ function course_scripts() {
 		// Enqueque theme scripts.
 		wp_enqueue_script( 'course-header', get_template_directory_uri() . '/assets/js/header.js', [], wp_get_theme()->get( 'Version' ), true );
 
-	}
-
-endif;
```
Comment (donnapep) [inline functions.php:59]: It's a bit weird that we're using `endif;` here when we don't use this style anywhere else in Sensei. Perhaps we could switch to regular `if` statements for consistency?

**Review by donnapep — APPROVED** [review]
Looks good! One small comment.

File: functions.php (hunk 1 above)
Comment (Imran92) [reply functions.php:59]: Yap, I was thinking about the same thing, maybe we can remove it in a separate PR
